var artistIndex = {

"Gabriel": "g0",
"Gabriel Faure": "g1",
"Gabriel Fauré": "g2",
"Gagné, Bernard": "g3",
"Gallagher": "g4",
"GammaRay": "g5",
"Gamma Ray": "g6",
"Gandhi Abdoula gagner": "g7",
"Garbage": "g8",
"Garotos Podres                        -                       Denis Iarossi": "g9",
"Gary Hoey": "g10",
"Gary Jules": "g11",
"Gary Moore": "g12",
"Gary Moore / Phil Lynot": "g13",
"Gary Numan": "g14",
"Gaspar Sanz": "g15",
"Gates Of Ishtar": "g16",
"Gates Of Yesterday": "g17",
"Gato com lebre": "g18",
"gave drohl": "g19",
"Gave Drohl": "g20",
"Gaze": "g21",
"Genesis": "g22",
"George Baker": "g23",
"George Gershwin": "g24",
"George Harrison": "g25",
"Georges Brassens": "g26",
"Georges BRASSENS": "g27",
"Georges Gershwin": "g28",
"George Shering": "g29",
"Georges Moustaki": "g30",
"Georges MOUSTAKI": "g31",
"George Strait": "g32",
"Gérald de Palmas": "g33",
"Gérard Lenormand": "g34",
"Gerardo Nunez": "g35",
"Gershwin": "g36",
"G.F.Händel": "g37",
"G.F. Händel": "g38",
"Giancarlo": "g39",
"Giancarlo Marinello": "g40",
"Gianluca Piersanti": "g41",
"Gigi d'agostino": "g42",
"Gigi d' Agostino": "g43",
"gilberto gil": "g44",
"Gilberto Gil": "g45",
"Gilbert Paul": "g46",
"Gilbert, Paul": "g47",
"Gillian Welch": "g48",
"Gilly": "g49",
"Gilly Barr": "g50",
"Giovanni Unterberger": "g51",
"Gipsy Kings": "g52",
"Gipsy Kings ": "g53",
"Gladiators": "g54",
"glassjaw": "g55",
"Glassjaw": "g56",
"Glass Jaw": "g57",
"GlassJAw": "g58",
"glay": "g59",
"Glay": "g60",
"GLAY": "g61",
"Glenn Campbell ": "g62",
"Glen Weston": "g63",
"Gluecifer": "g64",
"Gluters": "g65",
"Gob": "g66",
"Godsmack": "g67",
"God's Puke": "g68",
"Going Inside": "g69",
"gokhan mertler": "g70",
"Goldfinger": "g71",
"Goldman": "g72",
"Goldwater": "g73",
"gomez": "g74",
"Gone2far": "g75",
"good charlotte": "g76",
"Good charlotte": "g77",
"Good Charlotte": "g78",
"Good Charolett": "g79",
"Good Riddance": "g80",
"Goo Goo Dolls": "g81",
"Gordon Lightfoot": "g82",
"Gorgoroth": "g83",
"Gorillaz": "g84",
"Gorki": "g85",
"Gotthard": "g86",
"Gracemen": "g87",
"Grade 8": "g88",
"Graeme Allright": "g89",
"Graeme Allwright": "g90",
"Graeme John MacLennan": "g91",
"Graham, Davey ": "g92",
"Graham Wardrop": "g93",
"Grandaddy ": "g94",
"Grand Funk ": "g95",
"Grand Funk Railroad": "g96",
"Grand, Philippe ": "g97",
"Gran funk Railroad": "g98",
"Grateful Dead": "g99",
"Grave Axe": "g100",
"Grave Digger": "g101",
"Graveworm": "g102",
"Greame Allwright": "g103",
"Great White": "g104",
"Greek - Folk (Rembetiko)": "g105",
"Greenday": "g106",
"Green Day": "g107",
"Green Day ": "g108",
"Green Jelly": "g109",
"greg howe": "g110",
"Greg howe": "g111",
"Greg Howe": "g112",
"Greg Howe ": "g113",
"Greg Lake": "g114",
"Greg Nettles": "g115",
"Gren Day": "g116",
"Grieg": "g117",
"GRiNDSToNE": "g118",
"Grinspoon": "g119",
"Grip Inc.": "g120",
"Gronibard": "g121",
"GRONIBARD": "g122",
"Guano Apes": "g123",
"Guardian angel": "g124",
"GuitarCrazy": "g125",
"Guitar Heros (Joe Satriani, Steve Vai, Jason Becker, Y. Malmsteen, Van Halen...)": "g126",
"Guitar Master": "g127",
"Guitar Pro": "g128",
"Guitar_xxx": "g129",
"Gula": "g130",
"Guns and Roses": "g131",
"Guns N Fucking Roses": "g132",
"guns n roses": "g133",
"Guns 'n Roses": "g134",
"Guns 'n' Roses": "g135",
"Guns n' Roses": "g136",
"Guns 'N Roses": "g137",
"Guns N Roses": "g138",
"Guns N'Roses": "g139",
"Guns N' Roses": "g140",
"Guns N' Roses ": "g141",
"Guns nŽ Roses": "g142",
"Guns NŽ Roses": "g143",
"G. Unterberger": "g144",
"Gurhan Cagin": "g145",
"Gustavo Assis Brasil": "g146",
"Guttermouth": "g147",
"GWAR": "g148",
"Gypsy King": "g149"
};
