var artistIndex = {

"H20": "h0",
"H2O": "h1",
"Haggard": "h2",
"Hagizra Hagvoa": "h3",
"Halford": "h4",
"Half The World Away": "h5",
"halliday johnny": "h6",
"haluk levent": "h7",
"Haluk Levent": "h8",
"Hammer Chaos": "h9",
"hammer fall": "h10",
"Hammerfall": "h11",
"HammerFall": "h12",
"Hampton Hawes": "h13",
"Hank Williams": "h14",
"Harem Scarem": "h15",
"Harlem": "h16",
"Harold Faltermeyer / Steve Stevens": "h17",
"Harper Ben": "h18",
"Harrt Sacksioni": "h19",
"Harry Chapin": "h20",
"Harry Sacksioni": "h21",
"Hassan": "h22",
"Hatebreed": "h23",
"Hate Theory": "h24",
"Hatt": "h25",
"Hawkwind": "h26",
"Hayehudim": "h27",
"Hayehudim (The Jews)": "h28",
"H-Blockx": "h29",
"H-BLOCKX": "h30",
"HeadRace": "h31",
"Heart": "h32",
"Heavy Competition 6": "h33",
"Heavy Competition 7": "h34",
"Heavy Metal Guitar School": "h35",
"hector hellion": "h36",
"heideroosjes": "h37",
"Heideroosjes": "h38",
"Heitor Villalobos": "h39",
"Heitor Villa Lobos": "h40",
"Heitor Villa-Lobos": "h41",
"Heitor Villa-Lobos (1887-1959)": "h42",
"Helder Filipov": "h43",
"Hellacopters": "h44",
"Hell Awaits": "h45",
"Hellforge": "h46",
"Hell is For Heroes": "h47",
"Helloween": "h48",
"Helloween ": "h49",
"HELLOWEEN": "h50",
"Hell's Hilarious Happy Hour": "h51",
"Helmet": "h52",
"Helstar": "h53",
"HEMArOIds": "h54",
"Hemzemin": "h55",
"Hendrix": "h56",
"Hendrix, Jimi ": "h57",
"Henri Salvador": "h58",
"Henry Mancini": "h59",
"herman's hermits": "h60",
"Herman van Veen": "h61",
"Hermetica": "h62",
"Hermética": "h63",
"Heroes del silencio": "h64",
"Heroes del Silencio": "h65",
"Heroes Del Silencio": "h66",
"Héroes del Silencio": "h67",
"Héroes Del Silencio": "h68",
"Hey": "h69",
"hide": "h70",
"Hide": "h71",
"Hier is Leemhuis": "h72",
"HIGHLORD": "h73",
"Hillsong Music Australia": "h74",
"Him": "h75",
"HIM": "h76",
"HIM ": "h77",
"Hiroki Kikuta": "h78",
"Hives (The)": "h79",
"Hladno Pivo": "h80",
"Hoagy Carmichael": "h81",
"Hoerho": "h82",
"Hollow": "h83",
"Holocaust": "h84",
"Holyrays": "h85",
"HOME GROWN": "h86",
"Hoobastank": "h87",
"Hoobastank ": "h88",
"Hooverphonic": "h89",
"Horcas": "h90",
"Horkýe Slíe": "h91",
"Horkye Slize": "h92",
"horkýe slize": "h93",
"Horkyze Slize": "h94",
"House Of Guitars": "h95",
"Howard Shore": "h96",
"Hugo": "h97",
"Hullu": "h98",
"Hundred Reasons": "h99",
"Hurriganes": "h100",
"hury": "h101",
"Hybrid Theory": "h102",
"Hypocrisy": "h103"
};
