var artistIndex = {

"I Against I": "i0",
"Ian MacLennan": "i1",
"ibrahim turkan": "i2",
"Ibrahim Turkan": "i3",
"Ibunge": "i4",
"Iced Earth": "i5",
"Iced Earth - Tab: Speeddirt": "i6",
"Iconic": "i7",
"idlewild": "i8",
"Idlewild": "i9",
"ID Software": "i10",
"Iélou Baique": "i11",
"Iggy Kolan": "i12",
"Iggy Pop": "i13",
"Iggy Pop - The Stooges": "i14",
"Ignobilis": "i15",
"Igor Korneluk": "i16",
"IIIrd Tyme Out": "i17",
"ILL Mitch": "i18",
"Ill Nino": "i19",
"Ill Niño": "i20",
"illuminati": "i21",
"Illusion": "i22",
"Images": "i23",
"Imah": "i24",
"Immortal": "i25",
"Imortal Of Death": "i26",
"Impaled Nazarene": "i27",
"impelitteri": "i28",
"Impellitteri": "i29",
"Imperfect Picture": "i30",
"Inconnus (les)": "i31",
"incubus": "i32",
"Incubus": "i33",
"INCUBUS": "i34",
"Incubus feat. Big Punisher": "i35",
"Indigo Girls": "i36",
"indochine": "i37",
"Indochine": "i38",
"INDOCHINE": "i39",
"Indochine / Melissa Auf Der Maur": "i40",
"In Extremo": "i41",
"Infectious Grooves": "i42",
"Infinite Mass": "i43",
"Infinya": "i44",
"in flames": "i45",
"In flames": "i46",
"In Flames": "i47",
"In  Flames ": "i48",
"In Flames ": "i49",
"IN FLAMES": "i50",
"Ingo Marlos": "i51",
"Ingwie J. Malmsteen": "i52",
"Injected": "i53",
"InMe": "i54",
"InSane": "i55",
"Insomnium": "i56",
"Inspector Gadget": "i57",
"Inti illimani": "i58",
"Intrepid": "i59",
"Intwine": "i60",
"INXS": "i61",
"Iommi": "i62",
"Iron Fire": "i63",
"IronFist": "i64",
"IronFistLordCate": "i65",
"iron maiden": "i66",
"Iron maiden": "i67",
"Iron Maiden": "i68",
"Iron MaiDen": "i69",
"IRON MAIDEN": "i70",
"Iron Savior": "i71",
"Isaac Albeniz": "i72",
"Isaac Albéñiz": "i73",
"Ismael lo": "i74",
"Israel Vibration": "i75",
"Ivory Knight": "i76",
"ixuminimummassivum": "i77",
"Ixuminimummassivum": "i78",
"IXUMINIMUMMASSIVUM": "i79",
"Ixuminimummmassivum": "i80"
};
