var artistIndex = {

"Kabát": "k0",
"Kacofony": "k1",
"Kadiro": "k2",
"Kalle Päätalo": "k3",
"Kalmah": "k4",
"Kalmah ": "k5",
"Kamelot": "k6",
"Kana": "k7",
"kanec": "k8",
"Kansas": "k9",
"Kansas / Bluestream": "k10",
"Kashmir": "k11",
"Kat": "k12",
"KAT": "k13",
"Kataklysm": "k14",
"Katatonia": "k15",
"Kate Bush": "k16",
"Katherine Bolt": "k17",
"Kazik": "k18",
"Kazumi Watanabe": "k19",
"KD2A": "k20",
"Keb Mo": "k21",
"Keb' Mo' ": "k22",
"keep out": "k23",
"Kèíî": "k24",
"Kelly Osbourne and Ozzy": "k25",
"Kenny Loggins and Joe Messina": "k26",
"Kenny Wayne Shepherd": "k27",
"Kenny Wayne Sheppard": "k28",
"kent": "k29",
"Kent": "k30",
"Kepon": "k31",
"keren ann ": "k32",
"Keren Ann": "k33",
"Keren ann Zeidel": "k34",
"Kernundrum": "k35",
"Kesho": "k36",
"Kevin J. Manges (braumeister@centuryinter.net)": "k37",
"Kevin McMahon": "k38",
"khalil": "k39",
"khalil ": "k40",
"Kick Axe": "k41",
"Kickback": "k42",
"Kid Rock": "k43",
"Kid Rock and Sheryl Crow": "k44",
"Kikimax's Bountycrunch": "k45",
"Killers": "k46",
"KILLERS": "k47",
"Killswitch Engage": "k48",
"KIM CARNES": "k49",
"Kimura Maki": "k50",
"Kim Wilde": "k51",
"kingbees": "k52",
"King crimson": "k53",
"King Crimson": "k54",
"King diamond": "k55",
"King Diamond": "k56",
"KIng Diamond": "k57",
"KING DIAMOND": "k58",
"KING DIAMOND ": "k59",
"King Dimaond": "k60",
"Kingdom Come": "k61",
"King`s X": "k62",
"King's X": "k63",
"Kinks": "k64",
"KInks, The": "k65",
"Kino": "k66",
"Kirk Hammett": "k67",
"kirk hammet  tabbed by eliran kalisky": "k68",
"kiss": "k69",
"Kiss": "k70",
"KISS": "k71",
"kittie": "k72",
"Kittie": "k73",
"KITTIE": "k74",
"Kix": "k75",
"Klamydia": "k76",
"Klaus Weiland": "k77",
"KLB": "k78",
"Knightrider of Doom": "k79",
"Knopfler": "k80",
"Koichi Sugiyama": "k81",
"Koma": "k82",
"Komatozz": "k83",
"Kool Band": "k84",
"Koray Candemir": "k85",
"korn": "k86",
"koRn": "k87",
"Korn": "k88",
"KoRn": "k89",
"KORN": "k90",
"Korol i Shut": "k91",
"Korol i Shut ": "k92",
"Korol' i Shut": "k93",
"Korpiklaani": "k94",
"KoSaRn": "k95",
"Kotipelto": "k96",
"Kotiteollisuus": "k97",
"koyled": "k98",
"Koyled": "k99",
"Krasnaja Armija": "k100",
"Kravitz, Lenny": "k101",
"Kreator": "k102",
"Krematoriy (Russian rock band)": "k103",
"Krisiun": "k104",
"KRO": "k105",
"Krokus": "k106",
"Krux": "k107",
"Krystalknockt": "k108",
"Krytof": "k109",
"Krzysztof Zalewski - Loch Ness": "k110",
"k's choice": "k111",
"K's Choice": "k112",
"KtuLu": "k113",
"Kukulska Natalia": "k114",
"Kula Shaker": "k115",
"kurban": "k116",
"Kurban": "k117",
"Kuroyume": "k118",
"KuRsK": "k119",
"Kyo": "k120",
"kýraç": "k121",
"Kyuss": "k122"
};
