var artistIndex = {

"N/A": "n0",
"nada surf": "n1",
"Nadasurf": "n2",
"Nada Surf": "n3",
"Nada Surf  ": "n4",
"NADA SURF": "n5",
"Naftali Harzberger": "n6",
"Naglfar": "n7",
"Nailbed": "n8",
"Naithan": "n9",
"Nando Moraes": "n10",
"Nando Simas": "n11",
"Napalm Death": "n12",
"Narayan Gopal": "n13",
"Narciso Yepes": "n14",
"Nargaroth": "n15",
"Natalie Imbruglia": "n16",
"Natalie Imbruglia ": "n17",
"Natalie Imruglia": "n18",
"Natalie Merchant": "n19",
"Natas": "n20",
"NATAS": "n21",
"National Anthems": "n22",
"Nat King Cole": "n23",
"NAVIN": "n24",
"NAY": "n25",
"Neal Mccoy": "n26",
"Necromancer": "n27",
"Necrophagist": "n28",
"Negrita": "n29",
"Neila Abrahão": "n30",
"Neil Young": "n31",
"Neil Young and Crazy Horse": "n32",
"Nelson Faria": "n33",
"Nelson Faria (bossa nova)": "n34",
"Nena": "n35",
"Nenhum de Nos": "n36",
"Néophyte": "n37",
"Nerf Herder": "n38",
"Nettoie Les Têtes": "n39",
"Neurosis": "n40",
"Nevermore": "n41",
"New found Glory": "n42",
"New Found Glory": "n43",
"neznámy": "n44",
"Ne Zniu": "n45",
"Nguyen Duc Toan": "n46",
"N.H. Imber": "n47",
"Niccolo Paganini": "n48",
"Nicho Hinojosa": "n49",
"Nicholas Hiebert": "n50",
"Nicholas Tse": "n51",
"Nic Jones": "n52",
"Nick Carter": "n53",
"Nick Drake": "n54",
"Nickelback": "n55",
"Nickleback ": "n56",
"Nick Shepherd": "n57",
"Nicolai Rimsky-Korsakov": "n58",
"Nicolás.M": "n59",
"Nicolas Notarianni": "n60",
"Nicolas Peyrac": "n61",
"Nicolo Paganini": "n62",
"Night Guard": "n63",
"Nightingales": "n64",
"Night Ranger": "n65",
"Nightwish": "n66",
"NightWish": "n67",
"NIGHTWISH": "n68",
"NIGTHWISH": "n69",
"Nilsson": "n70",
"Nimbus": "n71",
"NIN": "n72",
"Nine inch Nails": "n73",
"Nine Inch Nails": "n74",
"Nine Inch Nails ": "n75",
"Nino Ferrer": "n76",
"Nino Rota": "n77",
"Nintendo": "n78",
"Nirnaeth": "n79",
"nirvana": "n80",
"Nirvana": "n81",
"Nirvana ": "n82",
"NIRVANA": "n83",
"Nixons": "n84",
"Njumen": "n85",
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN": "n86",
"nobue uematsu": "n87",
"nobuo uematsu": "n88",
"Nobuo Uematsu": "n89",
"Nocket Fool": "n90",
"Noctirne Silence": "n91",
"Nocturnal Pulse": "n92",
"No Degain": "n93",
"No Doubt": "n94",
"No fun at all": "n95",
"No Fun At All": "n96",
"Nofx": "n97",
"NoFx": "n98",
"NoFX": "n99",
"NOFX": "n100",
"No Hope": "n101",
"Noir desir": "n102",
"Noir Desir ": "n103",
"noir désir": "n104",
"Noir Désir": "n105",
"Noir Désir ": "n106",
"No Man's Land": "n107",
"Nonpoint": "n108",
"Nookie": "n109",
"Nookietoy": "n110",
"No one is innocent": "n111",
"No One Is Innocent": "n112",
"noonoors": "n113",
"Nootzaak": "n114",
"Norah Jones": "n115",
"Norba Zamboni": "n116",
"Noriko Mitose": "n117",
"Norman Blake": "n118",
"Norske The Kdis": "n119",
"Norther": "n120",
"NortheR": "n121",
"Northern throne": "n122",
"Northern Throne": "n123",
"No Soucy": "n124",
"Nostradameus": "n125",
"Nothing To Listen": "n126",
"Notre Dame de Paris": "n127",
"No use for a name": "n128",
"No Use for a Name": "n129",
"No Use For A Name": "n130",
"Nova era_Jose Rodolfo_jrbatica@onda.com.br": "n131",
"Nowhere Man": "n132",
"Nubou Uematsu": "n133",
"Nuno": "n134",
"Nuno Bettencourt": "n135"
};
