var artistIndex = {

"oasis": "o0",
"Oasis": "o1",
"OASIS": "o2",
"Obituary": "o3",
"obligation or reputation": "o4",
"Obliveon": "o5",
"Oblivion666": "o6",
"October Thorns": "o7",
"October Tide": "o8",
"ODIN": "o9",
"Of A Revolution": "o10",
"Office Of Strategic Influence (OSI)": "o11",
"offspring": "o12",
"Offspring": "o13",
"Offsprings": "o14",
"Offspring, The": "o15",
"Oficina G3": "o16",
"Ogres de Barback (Les)": "o17",
"Okuda Tamio": "o18",
"OLDFIELD Mike": "o19",
"Old Man's Child": "o20",
"Old Mans Child": "o21",
"Old Man Willow": "o22",
"Oleander": "o23",
"oleyire": "o24",
"Omar Aloulou": "o25",
"Omar Aloulou ": "o26",
"Omar Alouou": "o27",
"Omer Katzir": "o28",
"ONA": "o29",
"O.N.A.": "o30",
"ondes negatives": "o31",
"ondes négatives": "o32",
"ondes négatives, les": "o33",
"One Dollar Short": "o34",
"Onslaught": "o35",
"Opera IX": "o36",
"opeth": "o37",
"Opeth": "o38",
"Orange Seabobes": "o39",
"Orange Seabones": "o40",
"Orbiz": "o41",
"Orgy": "o42",
"original by  Hands Up": "o43",
"Osbourne, Ozzy": "o44",
"Osker": "o45",
"Osny": "o46",
"OS PARALAMAS DO SUCESSO": "o47",
"Osvaldo Farres": "o48",
"Otep": "o49",
"otherwise": "o50",
"Otherwise": "o51",
"OtherWise": "o52",
"Otis Redding": "o53",
"Ottmar Liebert": "o54",
"Our Lady Peace": "o55",
"Outkast": "o56",
"Out of Order": "o57",
"Output": "o58",
"OUTPUT": "o59",
"Overflow": "o60",
"Overkill": "o61",
"OVERKILL": "o62",
"Oxidus": "o63",
"Oxmoron": "o64",
"Oxolater": "o65",
"Oysterhed": "o66",
"Oz": "o67",
"Ozric Tentacles": "o68",
"Ozric Tenticals": "o69",
"Ozzy": "o70",
"Ozzy ": "o71",
"Ozzy Osborne": "o72",
"Ozzy Osbourne": "o73",
"Ozzy Osbourne ": "o74",
"OZZY OSBOURNE": "o75",
"Ozzy Osbourne / Zakk Wylde": "o76",
"Ozzy Ozbourne": "o77"
};
