var artistIndex = {

"u2": "u0",
"U2": "u1",
"U2 (Edge)": "u2",
"Uematsu, Nobuo": "u3",
"UFO": "u4",
"ugly kid joe": "u5",
"Ugly kid Joe": "u6",
"Ugly Kid Joe": "u7",
"Uknown": "u8",
"Uknown  T.V.": "u9",
"UK SUBS": "u10",
"Ulf W. Andersson": "u11",
"Uli Führe": "u12",
"Ultreia": "u13",
"Ulver": "u14",
"umfm": "u15",
"Unbekannt": "u16",
"uncommonmenfrommars": "u17",
"Uncommonmenfrommars": "u18",
"Unicornio": "u19",
"Unicornio cesar": "u20",
"Unicornio Cesar": "u21",
"Union 13": "u22",
"Unknow": "u23",
"unknown": "u24",
"Unknown": "u25",
"unknown artist": "u26",
"unkown": "u27",
"Unkown": "u28",
"Unkown but what for a talent !": "u29",
"Unkwown": "u30",
"Unleashed": "u31",
"Unloco": "u32",
"Unsane": "u33",
"Untitled": "u34",
"Untitled #3": "u35",
"Unwritten Law": "u36",
"Uriah Heep": "u37",
"Urlaub, Farin": "u38",
"Utada Hikaru": "u39",
"Uzeb": "u40"
};
