var artistIndex = {

"V8": "v0",
"Vader": "v1",
"Vagodin": "v2",
"Vagrant": "v3",
"Vai, Steve": "v4",
"Vai, Steve ": "v5",
"Valérie Duchateau": "v6",
"Valkyrie": "v7",
"Vama Veche": "v8",
"Vandenberg": "v9",
"Vanden Plas": "v10",
"Vanessa Carlton": "v11",
"Vanessa Paradis": "v12",
"Vangelis": "v13",
"Van halen": "v14",
"Van Halen": "v15",
"Vanilla Flavoured Fart": "v16",
"Vanilla Ice": "v17",
"Van Ky": "v18",
"Van Morrison": "v19",
"Various": "v20",
"Vasco Rossi": "v21",
"vast": "v22",
"Vaughan, Stevie Ray ": "v23",
"Vedran Hrenic": "v24",
"Vega4": "v25",
"Vein Lothario": "v26",
"Velikicirkussum": "v27",
"Velvet Underground (The)": "v28",
"Venäläinen kansanlaulu": "v29",
"Venom": "v30",
"Vertical Horizon": "v31",
"Vertical Slip": "v32",
"Vertigo Smog": "v33",
"Verve": "v34",
"Vex Red": "v35",
"Vic Mizzy": "v36",
"Victor Garcia": "v37",
"victor lopez": "v38",
"Victor López": "v39",
"Victor Wooten": "v40",
"Victor Wooten/Calelimaah": "v41",
"Village People": "v42",
"Vince Gill": "v43",
"Vincent Lafontaine et le St-Stan Band": "v44",
"Vinnie moore": "v45",
"Vinnie Moore": "v46",
"Vintersorg": "v47",
"Violent Femmes": "v48",
"Viper": "v49",
"Virsiä": "v50",
"Visdommen": "v51",
"viudas negras": "v52",
"Vivaldi": "v53",
"Vivaldi, Antonio": "v54",
"Vivaldi, Antonio ": "v55",
"Vivinopatch": "v56",
"Vixen": "v57",
"Vlad": "v58",
"Vladimir Misik": "v59",
"Vlatko Stefanovski": "v60",
"V.M.S. Algeciras": "v61",
"Voivod": "v62",
"Voïvod": "v63",
"Volovan": "v64",
"Voltage": "v65",
"Voodoo Glow Skulls": "v66",
"Vrävarna": "v67",
"Vulgaires Machins": "v68",
"VVB": "v69"
};
