var artistIndex = {

"Waldir Azevedo": "w0",
"WALLFLOWERS": "w1",
"Walter Giardino": "w2",
"W. A. Mozart": "w3",
"Wampas": "w4",
"Warcry": "w5",
"Warmen": "w6",
"Warrant": "w7",
"WASP": "w8",
"W.A.S.P.": "w9",
"Watcha": "w10",
"WATCHA": "w11",
"Wayne Shorter": "w12",
"Wayne Watson": "w13",
"Weather Report": "w14",
"Weathus": "w15",
"Webber, Lloyd ": "w16",
"Ween": "w17",
"weezer": "w18",
"Weezer": "w19",
"Weirdfred": "w20",
"WEIRDFRED": "w21",
"Weird Things for Weird People": "w22",
"Wereworm": "w23",
"Wes Montgomery": "w24",
"Wes MONTGOMERY": "w25",
"Westernhagen": "w26",
"Whateva Turns You On": "w27",
"Whatever": "w28",
"Wheatus": "w29",
"Wheatus ": "w30",
"WHEATUS": "w31",
"White lion": "w32",
"White Lion": "w33",
"Whitesnake": "w34",
"White Snake": "w35",
"White Stripes": "w36",
"White Stripes, The": "w37",
"White Widow": "w38",
"White Zombie": "w39",
"Whoyeah": "w40",
"Wild Cherry": "w41",
"william Kanengiser": "w42",
"Williams, John": "w43",
"Williams Mason": "w44",
"Williams, Mason": "w45",
"Will Weiglein": "w46",
"Willy Astor": "w47",
"willy wonka": "w48",
"Windfall": "w49",
"Winger": "w50",
"wings": "w51",
"Wings": "w52",
"Withered Beauty": "w53",
"Within Temptation": "w54",
"Wizard": "w55",
"Wizo": "w56",
"WOLFGANG": "w57",
"Wolfgang Amadeus Mozart": "w58",
"woodness": "w59",
"Woodness": "w60",
"Woody Allen+Goldie Hawn": "w61",
"Woody Guthrie": "w62",
"Words by Francis Scott Key Music by John Stafford Smith": "w63",
"WWF": "w64",
"Wyclef Jean feat. Mary J. Blige": "w65"
};
