var artistIndex = {

"Yamaoka Akira": "y0",
"Yannick Toillon, Yan Masson": "y1",
"Yann Tiersen": "y2",
"yan tiersenn": "y3",
"Yardbirds": "y4",
"Yasunori Mitsuda": "y5",
"Yavuz Cetin": "y6",
"Yavuz Çetin": "y7",
"Yehudit Ravitz , Yoni Rechter": "y8",
"Yellow": "y9",
"Yellow Bananas": "y10",
"Yellow (Cover of Pasexy)": "y11",
"Yes": "y12",
"Y.J.Malmsteen": "y13",
"Yngwei Malmsteen": "y14",
"Yngwie J Malmsteen": "y15",
"Yngwie J. Malmsteen": "y16",
"Yngwie J. Malmsteen's Rising Force": "y17",
"Yngwie JohannMalmsteen": "y18",
"Yngwie Malmsteem": "y19",
"yngwie malmsteen": "y20",
"Yngwie Malmsteen": "y21",
"Yngwie Malmsteen's Rising Force": "y22",
"Yngwie Mamlsteen": "y23",
"yo": "y24",
"Yo La Tengo": "y25",
"Yonatan Hakatan": "y26",
"Yoni Rechter+Yehudit ravitz": "y27",
"YU Grupa": "y28",
"Yuzo Koshiro": "y29",
"Yves DUTEIL": "y30"
};
