var artistIndex = {

"zacknafein": "z0",
"Zahal": "z1",
"Zakk Wylde": "z2",
"zander_the_commander": "z3",
"Zappa, Riccardo ": "z4",
"Zapper": "z5",
"Zazie": "z6",
"zebrahead": "z7",
"Zebrahead": "z8",
"ZebraHead": "z9",
"Zero Down": "z10",
"Zhang Zhen Yue": "z11",
"Zornik": "z12",
"Zortax": "z13",
"Z-row": "z14",
"Zuly": "z15",
"Zwan": "z16",
"Zyklon": "z17",
"ZZ top": "z18",
"ZZ Top": "z19",
"ZZ-Top": "z20",
"ZZTOP": "z21",
"Z Z TOP": "z22",
"ZZ TOP": "z23"